"""
Forge Type Generator

Automates generating a strict TypeScript `index.d.ts` file from Python type hints
exposed via the Bridge command registry.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List


class TypeGenerator:
    """Converts Python command schemas into TypeScript definitions."""

    def __init__(self, registry: List[Dict[str, Any]]):
        self.registry = registry

    def _python_to_ts_type(self, py_type: str) -> str:
        """Heuristic mapping from Python type string representations to TS."""
        # Clean up <class '...'> wrap
        py_type = re.sub(r"<class '([^']+)'>", r"\1", py_type)
        # Clean up generic typing prefix
        py_type = py_type.replace("typing.", "")

        # Handle lists first
        if "list" in py_type.lower() or "seq" in py_type.lower():
            if "dict" in py_type.lower() or "any" in py_type.lower():
                return "any[]"
            if "str" in py_type.lower():
                return "string[]"
            if "int" in py_type.lower() or "float" in py_type.lower():
                return "number[]"
            if "bool" in py_type.lower():
                return "boolean[]"
            return "unknown[]"

        if "dict" in py_type.lower():
            return "Record<string, unknown>"

        if "str" in py_type.lower():
            return "string"
            
        if "int" in py_type.lower() or "float" in py_type.lower():
            return "number"

        if "bool" in py_type.lower():
            return "boolean"

        if py_type == "NoneType" or py_type == "None" or py_type == "void":
            return "void"

        return "unknown"

    def _generate_command_signature(self, cmd: Dict[str, Any]) -> str:
        name = cmd["name"]
        schema = cmd.get("schema", {"args": [], "return_type": "Any"})
        
        args_strs = []
        for arg in schema.get("args", []):
            ts_type = self._python_to_ts_type(arg["type"])
            optional = "?" if arg.get("optional", False) else ""
            args_strs.append(f"{arg['name']}{optional}: {ts_type}")
            
        args_joined = ", ".join(args_strs)
        return_ts = self._python_to_ts_type(schema.get("return_type", "Any"))
        
        # All IPC calls return Promises in JS
        if return_ts == "void":
            return_ts = "void"
            promise_return = "Promise<void>"
        else:
            promise_return = f"Promise<{return_ts}>"
            
        return f"{name}({args_joined}): {promise_return};"

    def generate(self) -> str:
        """Generate the complete index.d.ts source string."""
        
        # Group commands by module prefix (e.g. fs_read -> fs.read)
        # Commands with no obvious prefix or inside internal namespace
        # get grouped under standard API endpoints, or exposed flat.
        
        groups: Dict[str, List[str]] = {}
        flat_commands: List[str] = []

        # List of capabilities we group into sub-interfaces
        sub_namespaces = [
            "fs", "dialog", "clipboard", "window", "runtime", 
            "notifications", "updater", "menu", "tray", "deepLink", "app", 
            "shortcuts", "screen", "power", "lifecycle", "keychain", "system"
        ]

        for cmd in self.registry:
            name = cmd["name"]
            
            # Skip internal framework introspections
            if name.startswith("__forge_"):
                continue

            placed = False
            for ns in sub_namespaces:
                prefix = f"{ns}_"
                if name.startswith(prefix):
                    groups.setdefault(ns, []).append(self._generate_command_signature(cmd))
                    placed = True
                    break
            
            if not placed:
                flat_commands.append(self._generate_command_signature(cmd))

        out = [
            "/**",
            " * Forge Automatically Generated TypeScript API",
            " * Do not edit this file manually.",
            " */",
            "",
            "export interface InvokeDetailedOptions {",
            "  detailed?: boolean;",
            "  trace?: boolean;",
            "}",
            ""
        ]

        # Generate Sub-Interfaces
        interface_names = {}
        for ns, cmds in groups.items():
            if not cmds:
                continue
            
            interface_name = f"Forge{ns.capitalize()}Api"
            interface_names[ns] = interface_name
            
            out.append(f"export interface {interface_name} {{")
            for cmd_str in cmds:
                # remove prefix from method name inside the interface
                inner_name = cmd_str.replace(f"{ns}_", "", 1)
                # camelCase conversion for specific multi-word things if needed
                # (for now, simply strip prefix)
                out.append(f"  {inner_name}")
            out.append("}")
            out.append("")

        # Global API interface
        out.append("export interface ForgeApi {")
        out.append('  invoke(command: string, args?: Record<string, unknown>): Promise<unknown>;')
        out.append('  invokeDetailed(command: string, args?: Record<string, unknown>, options?: InvokeDetailedOptions): Promise<unknown>;')
        out.append('  on(eventName: string, handler: (payload: unknown) => void): unknown;')
        out.append('  once(eventName: string, handler: (payload: unknown) => void): unknown;')
        out.append('  off(eventName: string, handler: (payload: unknown) => void): unknown;')
        
        for ns, interface_name in interface_names.items():
            out.append(f"  {ns}: {interface_name};")
            
        for cmd_str in flat_commands:
            out.append(f"  {cmd_str}")

        out.append("}")
        out.append("")
        
        out.append("export declare function isForgeAvailable(): boolean;")
        out.append("export declare function getForge(): ForgeApi;")
        out.append("export declare function invoke(command: string, args?: Record<string, unknown>): Promise<unknown>;")
        out.append("export declare function invokeDetailed(command: string, args?: Record<string, unknown>, options?: InvokeDetailedOptions): Promise<unknown>;")
        out.append("export declare function on(eventName: string, handler: (payload: unknown) => void): unknown;")
        out.append("export declare function once(eventName: string, handler: (payload: unknown) => void): unknown;")
        out.append("export declare function off(eventName: string, handler: (payload: unknown) => void): unknown;")
        out.append("export declare const forge: ForgeApi;")
        out.append("export default forge;")
        out.append("")

        return "\n".join(out)
