"""
Forge Framework TypeScript Generation.

Dynamically maps Python command signatures from the IPC bridge
into strongly-typed TypeScript declarations (`forge.d.ts`), enabling
seamlessly fully-typed client development (similar to tauri-apps/api).
"""

from __future__ import annotations

import inspect
from collections.abc import Callable
from typing import Any, get_args, get_origin

try:
    from typing import get_type_hints
except ImportError:
    get_type_hints = getattr(inspect, "get_annotations", None)  # type: ignore[assignment]


class TypeGenerator:
    """Generates `.d.ts` TypeScript definitions for a given set of Python functions."""

    def __init__(self) -> None:
        self.type_mappings: dict[Any, str] = {
            str: "string",
            int: "number",
            float: "number",
            bool: "boolean",
            list: "any[]",
            dict: "Record<string, any>",
            Any: "any",
            type(None): "null",
        }

    def _resolve_ts_type(self, py_type: Any) -> str:
        """Heuristically map Python type annotations to TypeScript types."""
        if py_type == inspect.Signature.empty:
            return "any"

        # Check exact mapping
        if py_type in self.type_mappings:
            return self.type_mappings[py_type]

        # Handle Optional/Union primitives via get_origin
        origin = get_origin(py_type)
        if origin is not None:
            args = get_args(py_type)
            # Handle List/Dict with inner types
            if origin in (list, list):
                inner_type = self._resolve_ts_type(args[0]) if args else "any"
                return f"{inner_type}[]"
            elif origin in (dict, dict):
                value_type = self._resolve_ts_type(args[1]) if len(args) > 1 else "any"
                return f"Record<string, {value_type}>"
            elif origin.__name__ == "Union":
                # Handle fast Optional[T] which is Union[T, NoneType]
                types = [self._resolve_ts_type(arg) for arg in args if arg is not type(None)]
                base = " | ".join(types) if types else "any"
                if type(None) in args:
                    return f"{base} | null"
                return base

        # Fallback for complex classes
        if getattr(py_type, "__name__", None):
            if py_type.__name__ == "dict":
                return "Record<string, any>"
            if py_type.__name__ == "list":
                return "any[]"

        return "any"

    def _generate_function_signature(self, cmd_name: str, func: Callable) -> str:
        """Parse `inspect.signature` to a TS invoke overload."""
        try:
            hints = get_type_hints(func) if get_type_hints else {}  # type: ignore[truthy-function]
            sig = inspect.signature(func)

            # Extract arguments
            ts_params = []
            for name, param in sig.parameters.items():
                if name == "self":
                    continue

                param_type = hints.get(name, param.annotation)
                ts_type = self._resolve_ts_type(param_type)

                is_optional = param.default != inspect.Parameter.empty
                ts_name = f"{name}?" if is_optional else name
                ts_params.append(f"{ts_name}: {ts_type}")

            # Define args object payload structure
            args_type = f"{{ {', '.join(ts_params)} }}" if ts_params else "Record<string, never>"

            # Extract return type
            ret_type = hints.get("return", sig.return_annotation)
            ts_return = self._resolve_ts_type(ret_type)
            if ts_return == "any":
                ts_return = "unknown"

            # Forge's internal structure: invoke('cmd_name', args, meta?)
            return f"    invoke(command: '{cmd_name}', args: {args_type}, meta?: Record<string, any>): Promise<{ts_return}>;"  # noqa: E501
        except Exception:
            # Safe boundary fallback for un-parseable functions (like C extensions or bad hints)
            return f"    invoke(command: '{cmd_name}', args?: Record<string, any>, meta?: Record<string, any>): Promise<any>; // Fallback due to parse error"  # noqa: E501

    def generate(self, commands: dict[str, Callable]) -> str:
        """Generate the global Window declarations for all registered commands."""
        buffer = [
            "// Auto-generated by Forge Framework's TypeGenerator.",
            "// Do not edit manually.",
            "",
            "declare global {",
            "  interface Window {",
            "    __forge__: {",
        ]

        # Sort commands for consistent emit behavior
        sorted_cmds = sorted(commands.keys())
        for cmd in sorted_cmds:
            buffer.append(self._generate_function_signature(cmd, commands[cmd]))

        # Append generic fallback overload so users can call unregistered/dynamic commands (if permitted by capability) safely  # noqa: E501
        buffer.append(
            "    invoke(command: string, args?: Record<string, any>, meta?: Record<string, any>): Promise<any>;"  # noqa: E501
        )

        buffer.extend(["    };", "  }", "}", "", "export {};", ""])

        return "\n".join(buffer)
